[platformio]
default_envs = waveshare_esp32_s3_lcd_1_69

[env:waveshare_esp32_s3_lcd_1_69]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 921600
debug_tool = esp-builtin
debug_init_break = tbreak setup
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_type = debug
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCONFIG_SPIRAM_USE_CAPS_ALLOC
lib_deps =
  https://github.com/moononournation/Arduino_GFX.git#v1.4.9
  https://github.com/bitbank2/JPEGDEC.git
  https://github.com/pschatzmann/arduino-libhelix.git
